// database
const DATABASE = {
  DATABASE_URL: 'DATABASE_URL',
} as const;

const REDIS = {
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
} as const;

const OAUTH_SOCIALS = {
  KAKAO_CLIENT_ID: 'KAKAO_CLIENT_ID',
  KAKAO_SECRET_KEY: 'KAKAO_SECRET_KEY',
  // GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  // GOOGLE_SECRET_KEY: 'GOOGLE_SECRET_KEY',
  // APPLE_CLIENT_ID : 'APPLE_CLIENT_ID',
  // APPLE_SECRET_KEY : 'APPLE_SECRET_KEY',
} as const;

const ENV_KEY = {
  SERVER_PORT: 'SERVER_PORT',
  NODE_ENV: 'NODE_ENV',
  ...DATABASE,
  ...REDIS,
  ...OAUTH_SOCIALS,
} as const;

export default ENV_KEY;
