// database
const DATABASE = {
  DATABASE_URL: 'DATABASE_URL',
} as const;

const REDIS = {
  REDIS_HOST: 'REDIS_HOST',
  REDIS_PORT: 'REDIS_PORT',
} as const;

const OAUTH_SOCIALS = {
  KAKAO_CLIENT_ID: 'KAKAO_CLIENT_ID',
  KAKAO_SECRET_KEY: 'KAKAO_SECRET_KEY',
  KAKAO_CALLBACK_URL: 'KAKAO_CALLBACK_URL',
  GOOGLE_CLIENT_ID: 'GOOGLE_CLIENT_ID',
  // GOOGLE_SECRET_KEY: 'GOOGLE_SECRET_KEY',
  // APPLE_CLIENT_ID : 'APPLE_CLIENT_ID',
  // APPLE_SECRET_KEY : 'APPLE_SECRET_KEY',
} as const;

const AWS = {
  AWS_REGION: 'AWS_REGION',
  AWS_ACCESS_KEY: 'AWS_ACCESS_KEY',
  AWS_SECRET_ACCESS_KEY: 'AWS_SECRET_ACCESS_KEY',
  AWS_S3_BUCKET_NAME: 'AWS_S3_BUCKET_NAME',
} as const;

const JWT = {
  JWT_SECRET_KEY: 'JWT_SECRET_KEY',
  JWT_ACCESS_TOKEN_EXPIRATION: 'JWT_ACCESS_TOKEN_EXPIRATION',
  JWT_ACCESS_TOKEN_EXPIRATION_TTL: 'JWT_ACCESS_TOKEN_EXPIRATION_TTL',
} as const;

const ENV_KEY = {
  SERVER_PORT: 'SERVER_PORT',
  NODE_ENV: 'NODE_ENV',
  ...DATABASE,
  ...REDIS,
  ...OAUTH_SOCIALS,
  ...AWS,
  ...JWT,
} as const;

export default ENV_KEY;
