name: Build And Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      current_time: ${{ steps.set_time.outputs.current_time }}
    steps:
      - name: Get current time
        id: set_time
        run: echo "::set-output name=current_time::$(date +'%Y%m%d_%H%M')" >> $GITHUB_ENV
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
      - name: Docker Build And Push
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/trazzle-api:${{ steps.set_time.outputs.current_time }} .
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/trazzle-api:${{ steps.set_time.outputs.current_time }}
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Access to Remove Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          script: |
            docker rm -f $(docker ps -aq) >/dev/null 2>&1
            docker rmi -f $(docker images -q) >/dev/null 2>&1
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/trazzle-api:${{ needs.build.outputs.current_time }}