name: Build And Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Access to Remove Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          script: |
            docker rm -f $(docker ps -aq) >/dev/null 2>&1
            docker rmi -f $(docker images -q) >/dev/null 2>&1
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/trazzle-api:20240328_0839
            docker run -d -p 80:10655 \
            -e NODE_ENV=production \
            -e SERVER_PORT=10655 \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/trazzle-api:20240328_0839