name: Build And Deploy
on:
  push:
    branches:
      - master

jobs:
#  build:
#    runs-on: ubuntu-latest
#    outputs:
#      current_time: ${{ steps.current_time.outputs.time }}
#    steps:
#      - name: Set Current Timestamp
#        id: current_time
#        run: echo "::set-output name=time::$(date +'%Y%m%d_%H%M')"
#      - name: Use current time
#        run: echo "The current time is ${{ steps.current_time.outputs.time }}"
#      - name: Checkout Repository
#        uses: actions/checkout@v2
#      - name: Set up Node.js
#        uses: actions/setup-node@v2
#        with:
#          node-version: '20'
#      - name: Docker Build And Push
#        run: |
#          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/trazzle-api:${{ steps.current_time.outputs.time }} .
#          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
#          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/trazzle-api:${{ steps.current_time.outputs.time }}
  deploy:
    runs-on: ubuntu-latest
#    needs: build
    steps:
      - name: Access to Remove Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_SERVER_HOST }}
          port: ${{ secrets.REMOTE_SERVER_PORT }}
          username: ${{ secrets.REMOTE_SERVER_USERNAME }}
          password: ${{ secrets.REMOTE_SERVER_PASSWORD }}
          script: |
            docker rm -f $(docker ps -aq) >/dev/null 2>&1
            docker rmi -f $(docker images -q) >/dev/null 2>&1
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/trazzle-api:20240328_0839
            docker run -d -p 80:10655 --name trazzle-api \
            -e NODE_ENV=production \
            -e SERVER_PORT=10655 \
            -e DB_USER=${{ secrets.DB_USER }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
#            -e DB_HOST=${{ secrets.DB_HOST }} \
#            -e DB_PORT=${{ secrets.DB_PORT }} \
#            -e DB_NAME=${{ secrets.DB_NAME }} \
            -e DATABASE_URL=${{ secrets.DATABASE_URL }} \
            -e REDIS_HOST=${{ secrets.REDIS_HOST }} \
            -e REDIS_PORT=${{ secrets.REDIS_PORT }} \
            -e KAKAO_CLIENT_ID=${{ secrets.KAKAO_CLIENT_ID }} \
            -e KAKAO_SECRET_KEY=${{ secrets.KAKAO_SECRET_KEY }} \
            -e KAKAO_CALLBACK_URL=${{ secrets.KAKAO_CALLBACK_URL }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e APPLE_CLIENT_ID=TBD \
            -e AWS_REGION=${{ secrets.AWS_REGION }} \
            -e AWS_ACCESS_KEY=${{ secrets.AWS_ACCESS_KEY }} \
            -e AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }} \
            -e AWS_S3_BUCKET_NAME=${{ secrets.AWS_S3_BUCKET_NAME }} \
            -e JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }} \
            -e JWT_ACCESS_TOKEN_EXPIRATION=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION }} \
            -e JWT_ACCESS_TOKEN_EXPIRATION_TTL=${{ secrets.JWT_ACCESS_TOKEN_EXPIRATION_TTL }} \
            ${{ secrets.DOCKER_HUB_USERNAME }}/trazzle-api:20240328_0839